org.gradle.jvmargs=-Xmx2G

maven_group=com.terraformersmc
archives_base_name=terrestria
mod_version=dev
single_platform=fabric

minecraft_version=26.1
loader_version=0.18.6
fabric_version=0.145.1+26.1

# Terraform modules
terraform_biome_remapper_api_version=17.0.0-beta.2
terraform_config_api_version=17.0.0-beta.2
terraform_dirt_version=17.0.0-beta.2
terraform_shapes_api_version=17.0.0-beta.2
terraform_surfaces_api_version=17.0.0-beta.2
terraform_tree_api_version=17.0.0-beta.2
terraform_wood_api_version=17.0.0-beta.2

# Biolith for worldgen module and testing
biolith_version=3.6.0-alpha.6

##
## Ferry configuration
##

# Project Metadata
project_name=Terrestria
project_owner=Terraformers
project_url=https://modrinth.com/mod/terrestria
# Explicitly link to a fixed commit so that the image links don't break in the future
project_logo=https://raw.githubusercontent.com/TerraformersMC/Terrestria/f2d93cc7fc09f26a0e8650702fa43e2cc59ef8d0/banners/Terrestria-logo-512x512.png
project_color=#0041bb
# default_release_type can be stable, beta, or alpha
default_release_type=alpha

# CurseForge Metadata
curseforge_slug=terrestria
curseforge_id=323974
curseforge_game_versions=26.1, 26.1.1, 26.1.2
curseforge_required_dependencies=fabric-api
curseforge_optional_dependencies=
curseforge_embedded_dependencies=biolith

# Modrinth Metadata
modrinth_slug=terrestria
modrinth_id=lsUDPMOT
modrinth_game_versions=26.1, 26.1.1, 26.1.2
modrinth_mod_loaders=
modrinth_required_dependencies=fabric-api
modrinth_optional_dependencies=
modrinth_embedded_dependencies=biolith

# Discord Emotes
curseforge_emote=<:curseforge:1078567270239981628>
modrinth_emote=<:modrinth:802414390510354453>
github_emote=<:github:698031289223217152>

# Webhook Options
use_project_username=false

# Changelog Options
# changelog_hide_unimportant_commits tries to hide Merge commits at the moment
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10
