base.archivesName = "terrestria-worldgen"

loom {
	accessWidenerPath = file("src/main/resources/terrestria-worldgen.accesswidener")
}

dependencies {
	// Biolith for the worldgen API module
	implementation "com.terraformersmc:biolith-fabric:${biolith_version}"

	implementation project(path: ':terrestria-common')
}
